version: "3.8"

services:
  app:
    build: ./src
    restart: unless-stopped
    container_name: app
    env_file:
      - .env
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000"]
      timeout: 30s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    container_name: mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 30s
        retries: 10
    # env_file:
    #   - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PWD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PWD}
    volumes:
      - mysql_db:/var/lib/mysql

volumes:
  mysql_db: